### ISSUE TITLE
RSS feed is missing

### ISSUE THREAD

**Issue by bpugh** [garoyeri/garoyeri-dev-site#7]
The site still shows `<link rel="alternate" type="application/rss+xml" href="https://www.garoyeri.dev/rss.xml" title="garoyeri.dev RSS Feed">` as the location of the feed but it's currently giving a 404.

Maybe it got excluded from deployment?

**Comment by garoyeri** [comment]
Ok, pushed some updates: upgraded the docusaurus libraries and theme to the latest beta, upgraded to NodeJS 16 on the build server, and that's pretty much it. Looks like it's there now :D
